spring:
  datasource:
    url: jdbc:mysql://121.124.124.8/dgrowth?characterEncoding=UTF-8
    username: dgrowth
    password: elrmfhtm@!
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jwt:
    secret: dlwltmtmvmfldqnxmtmxjel
    subject: voteJwt
    claims:
      user-id: uid
      platform-id: pid

logging.level:
  root: info
  org.hibernate.type: trace

